spring:
  application:
    name: twid

logging:
  level:
    io.lw900925.weibod: debug

weibod:
  weibo:
    api:
      base-url: https://m.weibo.cn/api
      cookie: ${user.dir}/config/cookie.txt
    dest-dir: ${user.dir}/downloads
    cache-dir: ${user.dir}/cache/timeline_id.json
    user-dir: ${user.dir}/config/list.txt
    retry-for-exceptions:
      - java.net.ProtocolException
      - java.net.SocketException
